import {VolunteeringDescription} from "../_models/VolunteeringDescription";

export const MyVolunteeringActivity: VolunteeringDescription[] = [
  {
    clubName: "Junior Entreprise INSAT",
    startMonth: "September",
    endMonth: "January",
    startYear:"2019",
    endYear:"2020",
    mission:"Head of Marketing Department",
    description:"",
    displayOnMain: true,
  },
  {
    clubName: "2éme Réunion Nationale Des Présidents - JCI Tunisie",
    startMonth: "April",
    endMonth: "October",
    startYear:"2019",
    endYear:"2019",
    mission:"Graphic Designer",
    description:"",
    displayOnMain: true,
  },
  {
    clubName: "Tunisian Aeroday",
    startMonth: "August",
    endMonth: "May",
    startYear:"2017",
    endYear:"2018",
    mission:"Student Ambassador",
    description:"",
    displayOnMain: true,
  },
  {
    clubName: "TedX INSAT",
    startMonth: "June",
    endMonth: "September",
    startYear:"2018",
    endYear:"2018",
    mission:"Graphic Designer",
    description:"",
    displayOnMain: false,
  },
  {
    clubName: "Insat Press",
    startMonth: "September",
    endMonth: "December",
    startYear:"2017",
    endYear:"2019",
    mission:"Photographer - Graphic Designer",
    description:"",
    displayOnMain: false,
  },
  {
    clubName: "Tunis Photography Club",
    startMonth: "September",
    endMonth: "",
    startYear:"2018",
    endYear:"now",
    mission:"Photographer",
    description:"",
    displayOnMain: true,
  },
];
